{% macro phone_region(phone_col, mobile_col) %}
case
    -- Greater London (020)
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '4420%' then 'Greater London'

    -- Scotland — 3-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44131%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44141%' then 'Scotland'

    -- North West — 3-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44151%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44161%' then 'North West'

    -- North East — 3-digit code
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44191%' then 'North East'

    -- Wales — Cardiff 029
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '4429%' then 'Wales'

    -- Northern Ireland — 028
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '4428%' then 'Northern Ireland'

    -- Yorkshire — 3-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44113%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44114%' then 'Yorkshire'

    -- Midlands — 3-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44115%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44116%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44121%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '4424%'  then 'Midlands'

    -- South West — 3-digit code
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44117%' then 'South West'

    -- South East — 3-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '44118%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '4423%'  then 'South East'

    -- Scotland — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441224%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441382%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441463%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441786%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441292%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441387%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441698%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441355%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441563%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441236%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441475%' then 'Scotland'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441389%' then 'Scotland'

    -- North East — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441642%' then 'North East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441429%' then 'North East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441325%' then 'North East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441388%' then 'North East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441670%' then 'North East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441434%' then 'North East'

    -- North West — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441772%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441253%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441524%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441204%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441942%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441257%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441695%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441282%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441254%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441706%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441625%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441270%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441606%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441244%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441928%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441925%' then 'North West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441229%' then 'North West'

    -- Yorkshire — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441482%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441904%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441423%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441924%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441274%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441709%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441302%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441977%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441484%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441422%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441535%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441756%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441723%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441947%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441609%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441748%' then 'Yorkshire'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441653%' then 'Yorkshire'

    -- Midlands — 5-digit codes (East and West combined)
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441332%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441246%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441773%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441636%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441522%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441476%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441664%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441455%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441536%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441604%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441327%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441933%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441902%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441782%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441384%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441922%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441543%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441785%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441827%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441530%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441743%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441952%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441584%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441905%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441562%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441386%' then 'Midlands'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441684%' then 'Midlands'

    -- South West — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441225%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441752%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441392%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441872%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441209%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441736%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441326%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441637%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441288%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441566%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441579%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441503%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441626%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441803%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441271%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441237%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441769%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441935%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441305%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441202%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441747%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441722%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441380%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441249%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441793%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441452%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441242%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441594%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441364%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441395%' then 'South West'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441297%' then 'South West'

    -- South East — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441273%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441483%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441293%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441252%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441256%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441962%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441489%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441983%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441843%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441227%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441303%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441304%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441622%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441732%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441892%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441342%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441444%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441903%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441243%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441329%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441494%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441753%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441628%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441344%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441276%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441420%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441264%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441737%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441372%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441428%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441798%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441825%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441323%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441424%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441296%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441865%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441235%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441491%' then 'South East'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441367%' then 'South East'

    -- East of England — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441603%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441234%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441473%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441284%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441206%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441245%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441702%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441268%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441279%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441727%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441442%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441582%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441767%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441480%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441733%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441553%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441493%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441502%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441379%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441263%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441328%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441362%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441366%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441908%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441992%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441707%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441438%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441462%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441223%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441353%' then 'East of England'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441638%' then 'East of England'

    -- Wales — 5-digit codes
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441633%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441792%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441267%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441437%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441970%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441654%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441286%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441248%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441492%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441745%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441352%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441978%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441824%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441873%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441495%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441443%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441685%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441656%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441446%' then 'Wales'
    when coalesce({{ phone_col }}, {{ mobile_col }}) like '441554%' then 'Wales'

    else null
end
{% endmacro %}
