name: 'trust_warehouse'
version: '1.0.0'
config-version: 2

profile: 'trust_warehouse'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  trust_warehouse:
    +schema: silver
    campaign_platform_mapping:
      +column_types:
        campaign_id: STRING

models:
  trust_warehouse:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
