trust_warehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:trust-pipeline"
      schema: main
      config_options:
        motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
